//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kreditrechner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kreditrechner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountUnscheduledRepaymentPlan {
            get {
                return ResourceManager.GetString("AmountUnscheduledRepaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateInstallmentPlan {
            get {
                return ResourceManager.GetString("DateInstallmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Plan.
        /// </summary>
        public static string InstallmentPlan {
            get {
                return ResourceManager.GetString("InstallmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Interest p.A.:.
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest.
        /// </summary>
        public static string InterestInstallmentPlan {
            get {
                return ResourceManager.GetString("InterestInstallmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Amount:.
        /// </summary>
        public static string LoanAmount {
            get {
                return ResourceManager.GetString("LoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Scenario.
        /// </summary>
        public static string LoanScenario {
            get {
                return ResourceManager.GetString("LoanScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum montly rate:.
        /// </summary>
        public static string MinimumMonthlyRate {
            get {
                return ResourceManager.GetString("MinimumMonthlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Repayment:.
        /// </summary>
        public static string MinimumRepayment {
            get {
                return ResourceManager.GetString("MinimumRepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month:.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MonthUnscheduledRepaymentPlan {
            get {
                return ResourceManager.GetString("MonthUnscheduledRepaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate:.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string RateInInstallmentPlan {
            get {
                return ResourceManager.GetString("RateInInstallmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining debt.
        /// </summary>
        public static string RemainingDebtInstallmentPlan {
            get {
                return ResourceManager.GetString("RemainingDebtInstallmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repayment at begin:.
        /// </summary>
        public static string RepaymentAtBegin {
            get {
                return ResourceManager.GetString("RepaymentAtBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repayment.
        /// </summary>
        public static string RepaymentInstallmentPlan {
            get {
                return ResourceManager.GetString("RepaymentInstallmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term:.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Interest:.
        /// </summary>
        public static string TotalInterest {
            get {
                return ResourceManager.GetString("TotalInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Repayment:.
        /// </summary>
        public static string TotalRepayment {
            get {
                return ResourceManager.GetString("TotalRepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeInstallmentPlan {
            get {
                return ResourceManager.GetString("TypeInstallmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unscheduled Payment.
        /// </summary>
        public static string UnscheduledPayment {
            get {
                return ResourceManager.GetString("UnscheduledPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unscheduled Payments Plan.
        /// </summary>
        public static string UnscheduledPaymentPlan {
            get {
                return ResourceManager.GetString("UnscheduledPaymentPlan", resourceCulture);
            }
        }
    }
}
